apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.2.0
appVersion: 0.0.5-1-PAGOPA-1007-migrazione-negative-biz-events-datastore
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
