apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.8.0
appVersion: 0.1.0-4-PAGOPA-1263-neg-broken-pipe-redis
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
