apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.11.0
appVersion: 0.2.3-1-PAGOPA-1454-sviluppo-biz-evt-migrazione-a-java-17
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
