microservice-chart:
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-negative-biz-events-datastore
    tag: "0.2.2"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuprod.bizevents.internal.platform.pagopa.it"
    path: /pagopa-negative-biz-events-datastore-service/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.6"
    limits:
      memory: "1536Mi"
      cpu: "1.0"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    WEBSITE_SITE_NAME: "pagopanegativebizeventsdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    COSMOS_DB_NAME: "db"
    COSMOS_DB_CONTAINER_NAME: "negative-biz-events"
    COSMOS_DB_URI: "https://pagopa-p-weu-bizevents-neg-ds-cosmos-account.documents.azure.com:443/"
    EVENT_HUB_NAMESPACE_1: "pagopa-p-evh-ns01"
    EVENT_HUB_NAMESPACE_2: "pagopa-p-evh-ns02"
    NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-biz-evt"
    AWAKABLE_NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-awakable-biz-evt"
    FINAL_NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-final-biz-evt"
    REDIS_HOST: "pagopa-p-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
    REDIS_EXPIRE_TIME_MS: "3600000" # an hour    
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    AzureWebJobsStorage: 'bizevent-p-azurewebjobsstorage'
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    NEGATIVE_EVENT_HUB_CONN_STRING: 'ehub-p-rx-negative-biz-connection-string'
    AWAKABLE_EVENTHUB_CONN_STRING: 'ehub-p-tx-awakable-negative-biz-connection-string'
    FINAL_EVENTHUB_CONN_STRING: 'ehub-p-tx-final-negative-biz-connection-string'
    COSMOS_CONN_STRING: 'cosmos-p-negative-biz-connection-string'
    REDIS_PWD: "redis-password"
    COSMOS_DB_PRIMARY_KEY: "cosmos-d-negative-biz-key"
    EVENT_HUB_TX_PRIMARY_KEY: "ehub-tx-d-negative-biz-key"
    EVENT_HUB_AWAKABLE_RX_CONNECTION_STRING: "ehub-rx-d-negative-awakable-biz-conn-string"
    EVENT_HUB_FINAL_RX_CONNECTION_STRING: "ehub-rx-d-negative-final-biz-conn-string"
  keyvault:
    name: "pagopa-p-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopanegativebizeventsdatastore
            namespaces: ["bizevents"]
            topologyKey: topology.kubernetes.io/zone
  canaryDelivery:
    create: false
    deployment:
      create: false
      image:
        tag: 0.5.6
