microservice-chart:
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-negative-biz-events-datastore
    tag: "0.1.0-3-PAGOPA-1263-neg-broken-pipe-redis"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 80
  ingress:
    create: true
    host: "weuprod.bizevents.internal.platform.pagopa.it"
    path: /pagopa-negative-biz-events-datastore-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1536Mi"
      cpu: "1.0"
    limits:
      memory: "1536Mi"
      cpu: "1.0"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: "pagopanegativebizeventsdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    COSMOS_DB_NAME: "db"
    COSMOS_DB_CONTAINER_NAME: "negative-biz-events"
    COSMOS_DB_URI: "https://pagopa-p-weu-bizevents-neg-ds-cosmos-account.documents.azure.com:443/"
    EVENT_HUB_NAMESPACE_1: "pagopa-p-evh-ns01"
    EVENT_HUB_NAMESPACE_2: "pagopa-p-evh-ns02"
    NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-biz-evt"
    AWAKABLE_NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-awakable-biz-evt"
    FINAL_NEGATIVE_EVENT_HUB_NAME: "nodo-dei-pagamenti-negative-final-biz-evt"
    REDIS_HOST: "pagopa-p-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
    REDIS_EXPIRE_TIME_MS: "3600000" # an hour
  envSecret:
    AzureWebJobsStorage: 'bizevent-p-azurewebjobsstorage'
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    NEGATIVE_EVENT_HUB_CONN_STRING: 'ehub-p-rx-negative-biz-connection-string'
    AWAKABLE_EVENTHUB_CONN_STRING: 'ehub-p-tx-awakable-negative-biz-connection-string'
    FINAL_EVENTHUB_CONN_STRING: 'ehub-p-tx-final-negative-biz-connection-string'
    COSMOS_CONN_STRING: 'cosmos-p-negative-biz-connection-string'
    REDIS_PWD: "redis-password"
    COSMOS_DB_PRIMARY_KEY: "cosmos-d-negative-biz-key"
    EVENT_HUB_TX_PRIMARY_KEY: "ehub-tx-d-negative-biz-key"
    EVENT_HUB_AWAKABLE_RX_CONNECTION_STRING: "ehub-rx-d-negative-awakable-biz-conn-string"
    EVENT_HUB_FINAL_RX_CONNECTION_STRING: "ehub-rx-d-negative-final-biz-conn-string"
  keyvault:
    name: "pagopa-p-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    deployment:
      image:
        tag: 0.1.0
    create: false
